# Site settings
title: Replacement Roof PA
email: tim@americanremodeling.net
description: >-
  Professional roof replacement services across Pennsylvania. 
  Quality materials, expert installation, and exceptional service for your home.
baseurl: "/replacement-roof-pa" # the subpath of your site, e.g. /blog
url: "https://tim-amredev.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  services:
    output: true
  testimonials:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# SEO settings
social:
  name: Replacement Roof PA
  links:
    - https://facebook.com/replacementroofpa
    - https://instagram.com/replacementroofpa

# Custom variables
phone: "(555) 123-4567"
address: "123 Main Street, Philadelphia, PA 19019"
