# Site settings
title: Replacement Roof PA
email: tim@americanremodeling.net
description: >-
  Professional roof replacement services across Pennsylvania. 
  Quality materials, expert installation, and exceptional service for your home.
baseurl: "/replacement-roof-pa"
url: "https://tim-amredev.github.io"
permalink: pretty

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  testimonials:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# Custom variables
phone: "(555) 123-4567"
address: "123 Main Street, Philadelphia, PA 19019"

