# Site settings
title: Replacement Roof PA
email: tim@americanremodeling.net
description: >-
  Professional roof replacement services across Pennsylvania. 
  Quality materials, expert installation, and exceptional service for your home.
baseurl: "" # Remove the subpath since we're serving from root
url: "https://replacementroofpa.com" # Update to actual domain
permalink: pretty

# Build settings
markdown: kramdown
sass:
  style: compressed
  sass_dir: _sass
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  testimonials:
    output: false

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - README.md

# SEO settings
social:
  name: Replacement Roof PA
  links:
    - https://facebook.com/replacementroofpa
    - https://instagram.com/replacementroofpa

# Custom variables
phone: "(555) 123-4567"
address: "123 Main Street, Philadelphia, PA 19019"

